### ISSUE TITLE
Get data

### ISSUE THREAD

**Issue by irwandwiyanto** [azu/pdf-slide-html#3]
How to get data page 1 if next or previous?

**Comment by azu** [comment]
What do you mean?

This cli is a generator for [pdf.js-controller](https://github.com/azu/pdf.js-controller).
If you want to get pdf page data, please refer to [PDF.js](https://github.com/mozilla/pdf.js).

**Comment by irwandwiyanto** [comment]
![image](https://github.com/azu/pdf-slide-html/assets/20964791/f092bf93-afe1-4657-bb7e-ea9ae1d43175)
sorry if my point is not understood. how to get the event when .js-next .js-prev is clicked, and new process data

**Comment by azu** [comment]
https://github.com/azu/slide-pdf.js/blob/7a171b4b13c0de1bee14768d44059e9f7915b7a2/index.js#L43-L44
These are just button elements. You can listen the click event.

It is difficult to know what to answer as specific use cases are not known.
